# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

defaults:
    run:
        working-directory: ./View

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
            - name: Install and Build 🔧
              run: |
                  npm install
                  CI=false npm run-script build
            - name: Deploy to Firebase 🔥
              uses: lowply/deploy-firebase@v0.0.2
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_PROJECT: smarter-days
