# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
            - name: Install and Build 🔧
              run: |
                  npm install --prefix ./View
                  CI=false npm run-script build --prefix ./View
            - name: Deploy to Firebase 🔥
              uses: lowply/deploy-firebase@v0.0.2
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_PROJECT: smarter-days
                  FOLDER: View
